### ISSUE TITLE
Add to docs that S3 can be a path (rather than just a bucket name)

### ISSUE THREAD

**Issue by Raab70** [drivendataorg/cookiecutter-data-science#109]
I think it's a bit of an odd restriction to require each project to have their own bucket in S3. Users should also be able to optionally specify a prefix for their files in S3 besides `/data/`. 

This way users could have `s3://my-data-science-bucket/project1/data/`

**Comment by pjbull** [comment]
Upated to add to docs that a user can specify `bucket/project` if they have a nested structure on s3. Happy to take a PR on this!

**Comment by pjbull** [comment]
Fixed in V2 docs
