### ISSUE TITLE
Create example projects that utilize Docker/Vagrant

### ISSUE THREAD

**Issue by jbrambleDC** [drivendataorg/cookiecutter-data-science#13]
It would be helpful to have examples of possible configurations. so we can show the community how to make this play well with docker/vagrant.

**Comment by pjbull** [comment]
Yeah agreed. Definitely worth setting up skeleton Dockerfile/Vagrantfile.

I think the barebones steps are:
 - base image (probably Ubuntu 14.04 or 16.04)
 - install virtualenv / virtualenv wrapper
 - clone repo (using the `repo_name`) variable
 - pip install requirements.txt

Could also include commented out steps to do things like:
 - make commands
 - run tests

**Comment by pjbull** [comment]
Moved to discussion in #379
