### ISSUE TITLE
Make separate docs pages instead of one monolithic page

### ISSUE THREAD

**Issue by pjbull** [drivendataorg/cookiecutter-data-science#19]
Especially if we're adding more content (e.g., #18), we may want to have a few separate pages. Possible segmentation could be:
- Project introduction and documentation
- Directory layout
- Opinions and philosophy
- Workflow components and the technologies that are chosen (or are options)
- Extension strategies (e.g., #16)
- Links to examples of projects that use the template

**Comment by elgehelge** [comment]
I love the one-page design. I love being able to send this page to people who have struggled with their project structure and say "Here, read this!".

**Comment by isms** [comment]
@pjbull Am inclined to close this issue. Thoughts?

**Comment by pjbull** [comment]
Fixed in v2
