### ISSUE TITLE
Add an opinion about making scripts chatty

### ISSUE THREAD

**Issue by pjbull** [drivendataorg/cookiecutter-data-science#20]
I'm generally in favor of keeping the opinions section pithy, but I think this may be a fit.
- Use real logging, not print statements (we have some boilerplate)
  - easy redirect to multiple places
  - timestamps and module for free
  - easy to see what happens on someone else's instance
- Include tqdm by default

**Comment by elgehelge** [comment]
+1 for tqdm
I am having a hard time imagining a python data science project which could not benefit from using tqdm

**Comment by pjbull** [comment]
Added some of this in the v2 scaffold. Closing for now.
