### ISSUE TITLE
Consider adding wemake-python-styleguide

### ISSUE THREAD

**Issue by sobolevn** [drivendataorg/cookiecutter-data-science#200]
## Description

I propose to add optional support of `wemake-python-styleguide`: https://github.com/wemake-services/wemake-python-styleguide

## Rationale

`wemake-python-styleguide` is a quite popular alternative for 3 tools at the same time: `flake8`, `pylint`, and `black`. See: https://github.com/wemake-services/wemake-python-styleguide#what-we-are-about

I saw that you are already using `flake8` as one of your requirements: that cool, but `wemake-python-styleguide` is `flake8` on steroids!

## Use case

`wemake-python-styleguide` is a very strict linter for python. It is based on `flake8` and has lots of checks. Literally 1000s of them. On the other hand it does not have type-related problems `pylint` has. It does not deal with type inference and does throw invalid violations at you.

It solves an important problem for many DS engineers: keeping their code consistent, pythonic, and error-free.

It can be also included to the project at any time, so existing users might benefit from it also, without any code rewrites. We use `flakehell` tool to allow legacy-first integrations.

There are multiple `cookiecutter` templates that already support this tool (like [`wemake-django-template`](https://github.com/wemake-services/wemake-django-template), so I thought it might be a good idea to add it here.

If you like this idea - I would be happy to help.

**Comment by pjbull** [comment]
We have all the tools here reflected except pylint. Closing for now, but feel free to open a tools discussion to gather support for pylint if you would like: https://github.com/drivendataorg/cookiecutter-data-science/discussions/categories/requested-tools
