### ISSUE TITLE
Add “apps” as a directory for model serving under main-project-stem

### ISSUE THREAD

**Issue by sugatoray** [drivendataorg/cookiecutter-data-science#226]
It is often necessary to share the model(s) with a user, the management, give a demo, etc. while only focusing on the functionality of the model(s) and keeping the code abstracted away. 

Jupyter notebooks can do only so much. Most common requirement in such scenarios is building an app and deploying it: Streamlit, FastAPI, Flask, etc. 

Although, perhaps some may argue that a separate repo with building the app keeps things more modular and cleaner, I would like to see what the community and the contributors have to say on this matter. 

So, can we consider adding an **apps** folder under the main repo-stem?

```bash
path: REPO/apps
```

**Comment by pjbull** [comment]
Since now in V2 the template a package by default (so "apps" could happily live in the base module), and the scaffold code is simplified, I am going to close this issue for now.
