### ISSUE TITLE
Real cases using the template

### ISSUE THREAD

**Issue by chaupmcs** [drivendataorg/cookiecutter-data-science#238]
Hi,

Thank you for making this useful template.
I just wonder if we have any real projects in which the template was used.
It would be helpful to see how the template works in concrete examples, what to write in the Makefile, etc.

Thank you!

**Comment by Pluriscient** [comment]
I came across this project for anyone that this remains of interest to:
https://github.com/cduvallet/microbiomeHD

**Comment by pjbull** [comment]
Closing in favor of having people post these in [Show and tell](https://github.com/drivendataorg/cookiecutter-data-science/discussions/categories/show-and-tell), which we just enabled.
