### ISSUE TITLE
More documentation for newcomers

### ISSUE THREAD

**Issue by KurtP20** [drivendataorg/cookiecutter-data-science#330]
Hi,
I am rather new to data science and Python, and wanted to try your data science template. I am struggling on many fronts, maybe you can address some of them in the documentation?
- What is the recommended design pattern for initializations, e.g. for the logger? Shouldn't there be something like an `src/init.py` file?
- Can you please elaborate why you use a makefile? In my understanding it should be possible to do everything from `main.py`, which to me would make more sense.
- Can you please describe the necessary steps to get the makefile working on Windows? It seems I need to install [this](https://gnuwin32.sourceforge.net/packages/make.htm), e.g. via `winget install GnuWin32.Make`. But then other commands, like `find` are missing. So does the makefile work at all on Windows, e.g. in Visual Studio Code?

**Comment by pjbull** [comment]
@KurtP20 With the V2 release the [docs](https://cookiecutter-data-science.drivendata.org/) have gotten a big update and the code scaffolding has evolved. Feel free to re-open if you've got additional requests.
