### ISSUE TITLE
ideas for documentation about just+pyproject.toml+mkdocs

### ISSUE THREAD

**Issue by epogrebnyak** [drivendataorg/cookiecutter-data-science#347]
`cookiecutter-data-science` has been foundational for me to learn data piplines, many thanks for creratign and maintaining it.

I have not visited for a while but recently recommended `cookiecutter-data-science` to someone, and came back, here are few ideas - maybe for documentation at least:

- [ ] `make` scares people, especailly of Windows, and I find https://github.com/casey/just command runner super helpful. it enables learning and you can try simple commands and extend them, extremely well-thought tool.
- [ ] what is someone wants `pyproject.toml` instead of `setup.py` and `requirements.txt` - it is probably awkwark to move entire project to `pyproject.toml`, but maybe say somehting about it in docs 
- [ ] https://www.mkdocs.org/ and `mkdocs-material` theme for the documentation? Sphinx is powerful tool, but so easy to get upset with it.

**Comment by pjbull** [comment]
Closing to move to discussions in #376 and #377. `mkdocs` is now available in v2.
