### ISSUE TITLE
config import fails when using V2 scaffolding

### ISSUE THREAD

**Issue by pjbull** [drivendataorg/cookiecutter-data-science#370]
At:
https://github.com/drivendataorg/cookiecutter-data-science/blob/master/%7B%7B%20cookiecutter.repo_name%20%7D%7D/%7B%7B%20cookiecutter.module_name%20%7D%7D/__init__.py#L1

Should be `from {{ cookiecutter.module_name }} import config`  # noqa: F401

------------

### Discussed in https://github.com/drivendataorg/cookiecutter-data-science/discussions/369

<div type='discussions-op-text'>

<sup>Originally posted by **wrighteap** May 27, 2024</sup>
Hi!

New cookiecutter user here. I just tried using your new v2 release.

I created a project project, repo repo and module module, using the code scaffold option. I selected conda as my environment manager, and requirements.txt for my dependency file. 

pip list shows the package module installed at /path/to/repo. When I try to import module, I get a ModuleNotFoundError: No module named 'config', due to the import config under module/__init__.py -- Is this a design choice to invite me to add /path/to/repo/module to sys path or to modify the config directly?

Sorry in advance if the question is inane or lacking in detail - happy to be told so or asked for additional information.</div>

**Comment by pjbull** [comment]
@wrighteap This should be fixed now. Would you mind testing for your use case? Make sure that when cookiecutter asks to re-clone the repo, you say yes so you get the latest.

**Comment by wrighteap** [comment]
@pjbull Hi. Sorry, clearly late on this. Using your latest version things work as expected. Thank you very much!
