### ISSUE TITLE
Add examples page and list to examples of analyses that use the project 

### ISSUE THREAD

**Issue by Foucl** [drivendataorg/cookiecutter-data-science#38]
Is there some way to link to a couple of projects/pipelines implementing this template? I know there are resources for every question I might have, but to see a whole project where all the parts you suggest here come together would be really helpful.

**Comment by pjbull** [comment]
Just tweeted out to see what's out there, feel free to spread the word: https://twitter.com/drivendataorg/status/751822257853440001

There are some examples if you search GitHub for "cookiecutter-data-science", but I'm hesitant to add links without the author's permission.

**Comment by pjbull** [comment]
Probably need to gather a few more, but here's a start based on what I could currently find on GitHub. Just fixed #39, so should be a little easier to identify:

 - Facebook Competition: https://github.com/jfconavarrete/kaggle-facebook

**Comment by Foucl** [comment]
Looks really good, thanks a Lot! And just in time, giving me even more inspiration for planning my thesis. I'll close this issue.

**Comment by pjbull** [comment]
Actually, let's leave it open until we get a couple more on the list, and then we'll add a page to the official docs with links. 🎆

**Comment by pjbull** [comment]
Another example:
https://github.com/inbo/alien-species-checklist

**Comment by lorey** [comment]
Also relevant for #59

**Comment by HemuManju** [comment]
Here are some links of my projects. 
[https://github.com/HemuManju/Reaction_time_classification](https://github.com/HemuManju/Reaction_time_classification)
[https://github.com/HemuManju/Dynamic_manipulation](https://github.com/HemuManju/Dynamic_manipulation)

**Comment by bkoseoglu** [comment]
Hi everyone,
here is a link to one of my project templates:
https://github.com/bkoseoglu/cookiecutter-data-science-example
You can also find an article explaining some parts of the template in here:
https://towardsdatascience.com/structure-your-data-science-projects-6c6c8653c16a

**Comment by pjbull** [comment]
Closing in favor of the "Show and Tell" category in discussions https://github.com/drivendataorg/cookiecutter-data-science/discussions/categories/show-and-tell
