### ISSUE TITLE
Add option to use different DAG manager

### ISSUE THREAD

**Issue by pjbull** [drivendataorg/cookiecutter-data-science#9]
We opt for a Makefile and GNU make by default. Could give options for some of these other projects:

[Paver](http://paver.github.io/paver/#)
[Luigi](http://luigi.readthedocs.org/en/stable/index.html)
[Airflow](http://pythonhosted.org/airflow/cli.html)
[Snakemake](https://bitbucket.org/snakemake/snakemake/wiki/Home)
[Ruffus](http://www.ruffus.org.uk/)
[Joblib](https://pythonhosted.org/joblib/memory.html)

**Comment by pjbull** [comment]
I'm starting to lean Snakemake as the default make tool given: (1) we're primarily supporting Python projects, (2) the DSL is less crazy than Make, (3) it won't be as annoying for Windows users to install.

**Comment by victormartingarcia** [comment]
+1 for allowing different DAG managers. 

Make is great, but IMHO there are much better/modern pipeline frameworks. My favourite [Airflow](https://medium.com/airbnb-engineering/airflow-a-workflow-management-platform-46318b977fd8)

**Comment by jamesmyatt** [comment]
Here's a cookiecutter I found using snakemake: https://github.com/xguse/cookiecutter-snakemake-analysis-pipeline

**Comment by pjbull** [comment]
Closing for now. Discussion on command runners / DAG tools other than `make` is available here: https://github.com/drivendataorg/cookiecutter-data-science/discussions?discussions_q=label%3Acommand-runner
